### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by ahmad420** [WebAhead7/PUZZLE#13]
Lovely background image 💯  nice work :D .

- there is something wrong with the images. ![PUZZLE-img](https://user-images.githubusercontent.com/53348451/96090968-a4c10900-0ed1-11eb-9eb7-655e8176ee63.png)

- also, you need to check the drag and drop at img2 -level 1 it's not working as it should. 

- You're doing great work, I truly value your effort and dedication 🥇 .

**Comment by OmklthomAmara** [comment]
updated version is avalabile now, you can check it.
thanks we appreciate it. 😄
