### ISSUE TITLE
Suggestion for code refactoring

### ISSUE THREAD

**Issue by MahmodMhamed** [WebAhead7/PUZZLE#14]
Instead we write 25 divs / images in html file, we can write a function in js file that creates them dynamically.

**Comment by MahmodMhamed** [comment]
Will be much easier to maintain one or two functions.
Let's imagine that we want to create a puzzle with 100 images, way too hard to maintain with html only.

**Comment by OmklthomAmara** [comment]
In a large scale it's a Good Idea.
Thanks ! 👍
