### ISSUE TITLE
Unable to finish the game.

### ISSUE THREAD

**Issue by alaabashiyi** [WebAhead7/PUZZLE#8]
1: unable to finish the game due to some weird bug where I cannot drag and drop the last 2 pieces.
2: when clicking return it does not reset the game, it stays there. (it might be a feature im not sure.)

![image](https://user-images.githubusercontent.com/29834132/96089995-46475b00-0ed0-11eb-97a4-b0cd44709aa8.png)

**Comment by OmklthomAmara** [comment]
1. Try Drag and Drop.

2. will be fixed.
